
apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 namespace: default
 labels:
   app: backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
     - name: flask-backend
       image: issactototototo/musicrec-backend:latest
       ports:
       - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000

   